// Code generated by "stringer -type=TimeFrame -linecomment"; DO NOT EDIT.

package clients

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Week-0]
	_ = x[Month-1]
	_ = x[ThreeMonth-2]
	_ = x[SixMonth-3]
	_ = x[Year-4]
	_ = x[Overall-5]
}

const _TimeFrame_name = "7day1month3month6month12monthoverall"

var _TimeFrame_index = [...]uint8{0, 4, 10, 16, 22, 29, 36}

func (i TimeFrame) String() string {
	if i < 0 || i >= TimeFrame(len(_TimeFrame_index)-1) {
		return "TimeFrame(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeFrame_name[_TimeFrame_index[i]:_TimeFrame_index[i+1]]
}
