name: CI Checks
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '~1.27.0' # The Go version to download (if necessary) and use.
      - name: Build Executable
        run: |
          go build
      - name: Run Tests
        run: |
          go test ./...
